name: fluttered
description: Fluttered
version: 0.0.1
author: null
homepage: null
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  mobx: ^0.1.0
  flutter_mobx: ^0.1.0
  dartla_util:
    git:
      url: 'git@github.com:kobiburnley/dartla-util.git'
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
