name: fluttered
description: Fluttered
version: 0.0.1
author: null
homepage: null
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dartla_util:
    path: ../dartla-util
  action_tree_flutter:
    path: ../action-tree/action_tree_flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
