version: 2
jobs:
  test:
    docker:
    - image: circleci/node:8.12.0
    - image: circleci/android:api-25-alpha
    steps:
    - add_ssh_keys:
        fingerprints:
        - "a9:96:04:48:62:9f:e1:d8:88:6d:25:89:26:e4:41:40"
    - checkout
    - run:
        name: Dart
        command: |
          wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.0.0-stable.tar.xz
          tar xf flutter_linux_v1.0.0-stable.tar.xz

          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile

          npm i -g multi-package-dart
          multi-package-dart generate --env ci --config config/multi-package/config.ci.json
          cat pubspec.yaml
    - run:
        name: Test
        command: |
          ./flutter/bin/flutter packages get
          ./flutter/bin/cache/dart-sdk/bin/dartanalyzer lib/*.dart

          git config --global user.email circleci@circleci.com
          git config --global user.name CircleCI

          git add 'pubspec.yaml'
          BEHIND=$(git status --untracked-files=no --porcelain)
          if test "$BEHIND" = \s+; then echo $BEHIND; else git commit -m 'Lock [skip ci]' && git push; fi

workflows:
  version: 2
  release:
    jobs:
    - test
