version: 2
jobs:
  test:
    docker:
    - image: circleci/android:api-25-alpha
    steps:
    - checkout
    - run:
        name: Dart
        command: |
          wget https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v0.5.1-beta.tar.xz
          tar xf flutter_linux_v0.5.1-beta.tar.xz

          wget https://nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x64.tar.xz
          tar xf node-v10.13.0-linux-x64.tar.xz

          wget https://registry.npmjs.org/multi-package-dart/-/multi-package-dart-1.0.4.tgz
          tar xf multi-package-dart-1.0.4.tgz

          ./node-v10.13.0-linux-x64/bin/node package/lib/main.js generate --env ci --config config/multi-package/config.ci.json
          cat pubspec.yaml
    - run:
        name: Test
        command: |
          ./flutter/bin/cache/dart-sdk/bin/dartanalyzer {lib,example}/*.dart
          ./flutter/bin/cache/dart-sdk/bin/pub run test
workflows:
  version: 2
  release:
    jobs:
    - test
