version: 2
jobs:
  test:
    docker:
    - image: circleci/node:8.12.0
    - image: circleci/android:api-25-alpha
    steps:
    - add_ssh_keys:
        fingerprints:
        - "eb:17:e1:f0:b6:81:70:e2:c0:fb:b6:a8:b0:a0:ec:6a"
    - checkout
    - run:
        name: Dart
        command: |
          wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.0.0-stable.tar.xz
          tar xf flutter_linux_v1.0.0-stable.tar.xz

          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile

          npm i -g multi-package-dart
          multi-package-dart generate --env ci --config config/multi-package/config.ci.json
          cat pubspec.yaml
    - run:
        name: Test
        command: |
          ./flutter/bin/flutter packages get
          ./flutter/bin/cache/dart-sdk/bin/dartanalyzer lib/*.dart
          ./flutter/bin/cache/dart-sdk/bin/pub run test
workflows:
  version: 2
  release:
    jobs:
    - test
